name: run-five-minutes-twitter

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: |
          python-version: 3.8
      - run: pip install -r requirements.txt
        env: |
          API_KEY = {{ secrets.API_KEY }}
          API_SECRETKEY = {{ secrets.API_SECRETKEY}}
          POCKET_CONSUMER_KEY = {{ secrets.POCKET_CONSUMER_KEY }}
          POCKET_ACCESS_TOKEN = {{ secrets.POCKET_ACCESS_TOKEN }}
      - run: python3 app.py 

